import React from 'react';

export function alertsVals(app) {
    const acards = [
      {
        stage: 'EXCEPTIONAL', stageBg: '#3a1140', stageFg: '#f06ee2', sym: '$GLYPH', chain: 'SOLANA', chainColor: '#8f7bff',
        title: 'EXCEPTIONAL — $GLYPH / SOLANA — Score 91, conf 0.91',
        body: 'Adjusted 5-minute volume is 9.1× baseline (robust z 6.2). Unique buyers up 4.0× — 71% first-time asset buyers. Net liquidity +$118K across 3 pools with 14 new LPs. Stablecoin rotation-in from 96 wallets exiting the AI cohort.',
        risks: 'Top-10 adjusted holders own 29%; token under 2h old (experimental baselines).',
        buttons: ['Open dashboard', 'Solscan', 'Mute 1h'], ts: '14:32:08', id: 'alert a-7f21', slug: 'glyph',
        fields: [{ k: 'SCORE', v: '91', c: '#f06ee2' }, { k: 'CONF', v: '0.91', c: '#ffffff' }, { k: 'VOL 5M ADJ', v: '$1.69M', c: '#4d8dff' }, { k: 'BUYERS 5M', v: '412', c: '#4d8dff' }, { k: 'LIQUIDITY', v: '$412K', c: '#ffffff' }, { k: 'WASH PROB', v: '6%', c: '#a3aed0' }]
      },
      {
        stage: 'CONFIRMED', stageBg: '#0e2a5c', stageFg: '#4d8dff', sym: 'NVDAx', chain: 'ROBINHOOD CHAIN', chainColor: '#4fc3f7',
        title: 'CONFIRMED ROTATION — NVDA STOCK TOKEN — Score 84, conf 0.87',
        body: 'Executed RFQ volume is 5.1× its session-adjusted baseline; unique takers up 2.7×. Capital is rotating from the tech-token cohort into semiconductors. Executions within 0.42% of Chainlink; contract canonical, oracle fresh, no multiplier pending.',
        risks: '61% of recent RFQ volume filled by one maker.',
        buttons: ['Open dashboard', 'Explorer', 'Mute 1h'], ts: '14:29:41', id: 'alert a-7f1d', slug: 'nvdax',
        fields: [{ k: 'SCORE', v: '84', c: '#4d8dff' }, { k: 'CONF', v: '0.87', c: '#ffffff' }, { k: 'RFQ VOL 15M', v: '$944K', c: '#4d8dff' }, { k: 'TAKERS', v: '151', c: '#4d8dff' }, { k: 'ORACLE DEV', v: '0.42%', c: '#4d8dff' }, { k: 'MAKER CONC', v: '61%', c: '#ff4fae' }]
      }];
    const pushBody = '$GLYPH / SOLANA hit EXCEPTIONAL (91). Vol 9.1×, buyers 4.0×, liq +$118K. Click to open the live feed.';
    const jsonLines = ['{', '  "alert_id": "a-7f21",', '  "stage": "exceptional",', '  "chain": "solana",', '  "token_address": "GLyPh…9xQz",', '  "final_score": 91,', '  "confidence": 0.91,', '  "organic_activity_probability": 0.94,', '  "signal_families": ["volume", "breadth",', '    "liquidity", "rotation"],', '  "reasons": [{ "code": "VOL_ANOM_5M",', '    "robust_z": 6.2, "ratio": 9.1 }, …],', '  "risk": { "wash_probability": 0.06,', '    "hard_veto": false },', '  "links": { "dashboard": "…", "solscan": "…" }', '}'];
    return { acards, pushBody, jsonLines };
  }

export default function AlertCards({ v, css }) {
  return v.isAlerts && <>
          <div data-screen-label="Alert cards" style={css("flex:1;overflow:auto;padding:12px 14px;min-height:0", { v })}><div style={css("display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;align-items:start", { v })}><div style={css("background:#0a1226;border:1px solid #1c2a4d;border-radius:10px;overflow:hidden", { v })}><div style={css("padding:8px 14px;border-bottom:1px solid #1c2a4d;font-size:9px;letter-spacing:1.2px;font-weight:700;color:#8b96b8", { v })}>TELEGRAM — @vibescreener_bot</div><div style={css("padding:12px;display:flex;flex-direction:column;gap:12px", { v })}>{(v.acards || []).map((a, i) => (<React.Fragment key={i}>
            <div style={css("background:#101c38;border-radius:14px 14px 14px 4px;padding:12px 14px", { v, a })}><div style={css("display:flex;gap:8px;align-items:center;margin-bottom:7px;flex-wrap:wrap", { v, a })}><span style={css("font-size:8.5px;font-weight:800;letter-spacing:.6px;padding:3px 9px;border-radius:999px;background:{{ a.stageBg }};color:{{ a.stageFg }}", { v, a })}>{a.stage}</span><span style={css("font-weight:800;color:#ffffff;font-size:13px", { v, a })}>{a.sym}</span><span style={css("font-size:9.5px;font-weight:600;color:{{ a.chainColor }}", { v, a })}>{a.chain}</span></div><div style={css("font-size:11px;color:#c6d1ea;line-height:1.6", { v, a })}>{a.body}</div><div style={css("margin-top:7px;font-size:11px;color:#c6d1ea;line-height:1.5", { v, a })}><span style={css("color:#f06ee2;font-weight:700", { v, a })}>Risks:</span> {a.risks}</div><div style={css("display:flex;gap:7px;margin-top:10px;flex-wrap:wrap", { v, a })}>{(a.buttons || []).map((b, i) => (<React.Fragment key={i}>
              <div className="hf6f5791f" style={css("padding:4px 12px;border-radius:999px;border:1px solid #2b6bff;color:#6ea0ff;font-size:9.5px;font-weight:700;cursor:pointer", { v, a, b })}>{b}</div>
            </React.Fragment>))}</div><div style={css("font-size:9px;color:#6b7699;margin-top:8px", { v, a })}>{a.ts} UTC · {a.id}</div></div>
          </React.Fragment>))}</div></div><div style={css("background:#0a1226;border:1px solid #1c2a4d;border-radius:10px;overflow:hidden", { v })}><div style={css("padding:8px 14px;border-bottom:1px solid #1c2a4d;font-size:9px;letter-spacing:1.2px;font-weight:700;color:#8b96b8", { v })}>DISCORD — #screener-alerts</div><div style={css("padding:12px;display:flex;flex-direction:column;gap:12px", { v })}>{(v.acards || []).map((a, i) => (<React.Fragment key={i}>
            <div style={css("display:flex;background:#101c38;border-radius:6px;overflow:hidden", { v, a })}><div style={css("width:4px;background:{{ a.stageFg }};flex-shrink:0", { v, a })}></div><div style={css("padding:11px 13px;min-width:0", { v, a })}><div style={css("font-size:9px;color:#8b96b8;margin-bottom:4px", { v, a })}>VibeScreener BOT · today at {a.ts}</div><div style={css("font-weight:800;color:#ffffff;font-size:12px;margin-bottom:5px", { v, a })}>{a.title}</div><div style={css("font-size:10.5px;color:#c6d1ea;line-height:1.55;margin-bottom:9px", { v, a })}>{a.body}</div><div style={css("display:grid;grid-template-columns:repeat(3,1fr);gap:7px 10px", { v, a })}>{(a.fields || []).map((f, i) => (<React.Fragment key={i}>
              <div><div style={css("font-size:8.5px;letter-spacing:.6px;color:#6b7699;font-weight:700", { v, a, f })}>{f.k}</div><div style={css("font-size:11px;font-weight:700;color:{{ f.c }}", { v, a, f })}>{f.v}</div></div>
            </React.Fragment>))}</div><div style={css("font-size:9px;color:#6b7699;margin-top:9px", { v, a })}>{a.id} · vibe.trading/screener/{a.slug}</div></div></div>
          </React.Fragment>))}</div></div><div style={css("display:flex;flex-direction:column;gap:10px", { v })}><div style={css("background:#0a1226;border:1px solid #1c2a4d;border-radius:10px;overflow:hidden", { v })}><div style={css("padding:8px 14px;border-bottom:1px solid #1c2a4d;font-size:9px;letter-spacing:1.2px;font-weight:700;color:#8b96b8", { v })}>BROWSER PUSH</div><div style={css("margin:14px;background:rgba(16,28,56,.95);border:1px solid #223052;border-radius:14px;padding:12px 14px;display:flex;gap:10px;box-shadow:0 10px 30px rgba(0,0,0,.45)", { v })}><img src="/assets/vibe-logo.png" alt="Vibe" style={css("width:34px;height:34px;object-fit:cover;object-position:left;border-radius:8px;flex-shrink:0", { v })} /><div style={css("min-width:0;flex:1", { v })}><div style={css("display:flex;justify-content:space-between;gap:8px", { v })}><span style={css("font-size:11px;font-weight:800;color:#ffffff", { v })}>VibeScreener — EXCEPTIONAL</span><span style={css("font-size:9px;color:#6b7699", { v })}>now</span></div><div style={css("font-size:10.5px;color:#c6d1ea;line-height:1.45;margin-top:2px", { v })}>{v.pushBody}</div></div></div></div><div style={css("background:#0a1226;border:1px solid #1c2a4d;border-radius:10px;overflow:hidden", { v })}><div style={css("padding:8px 14px;border-bottom:1px solid #1c2a4d;font-size:9px;letter-spacing:1.2px;font-weight:700;color:#8b96b8", { v })}>WEBHOOK PAYLOAD — ABBREVIATED</div><div style={css("padding:10px 14px", { v })}>{(v.jsonLines || []).map((l, i) => (<React.Fragment key={i}>
            <div style={css("font-size:9.5px;line-height:1.6;color:#a3aed0;white-space:pre;font-family:monospace", { v, l })}>{l}</div>
          </React.Fragment>))}</div></div><div style={css("background:#0a1226;border:1px solid #1c2a4d;border-radius:10px;padding:12px 14px;font-size:10px;color:#8b96b8;line-height:1.6", { v })}>Every channel renders from the same alert payload. Cards always state the metric, its baseline, and what could invalidate the signal — never a bare "volume up 300%".</div></div></div></div>
        </>
}
