import React from 'react';

export default function LiveOpportunities({ v, css }) {
  return v.isLive && (<>
          <div data-screen-label="Live opportunities" style={css("flex:1;display:flex;flex-direction:column;min-height:0", { v })}><div style={css("display:flex;gap:10px;padding:10px 14px;flex-shrink:0", { v })}>{(v.stats || []).map((s, i) => (<React.Fragment key={i}>
            <div style={css("flex:1;background:#0a1226;border:1px solid #1c2a4d;border-radius:10px;padding:8px 12px", { v, s })}><div style={css("font-size:9px;letter-spacing:1.2px;color:#8b96b8", { v, s })}>{s.label}</div><div style={css("font-size:17px;font-weight:600;margin-top:2px;color:{{ s.color }}", { v, s })}>{s.value}</div></div>
          </React.Fragment>))}</div><div style={css("display:flex;align-items:center;gap:6px;padding:0 14px 10px;flex-shrink:0;flex-wrap:wrap", { v })}><span style={css("font-size:9px;letter-spacing:1px;color:#6b7699;font-weight:600", { v })}>VIEW</span>{(v.views || []).map((v, i) => (<React.Fragment key={i}>
            <div className="h3eb549cf" onClick={v.go} style={css("padding:4px 12px;border-radius:999px;font-size:10px;font-weight:600;cursor:pointer;background:{{ v.bg }};color:{{ v.fg }};border:1px solid {{ v.bd }}", { v, v })}>{v.label}</div>
          </React.Fragment>))}<div style={css("width:1px;height:18px;background:#1c2a4d;margin:0 4px", { v })}></div>{(v.chainFilters || []).map((v, i) => (<React.Fragment key={i}>
            <div className="h3eb549cf" onClick={v.go} style={css("padding:4px 12px;border-radius:999px;font-size:10px;font-weight:600;cursor:pointer;background:{{ v.bg }};color:{{ v.fg }};border:1px solid {{ v.bd }}", { v, v })}>{v.label}</div>
          </React.Fragment>))}<div style={css("width:1px;height:18px;background:#1c2a4d;margin:0 4px", { v })}></div>{(v.classFilters || []).map((v, i) => (<React.Fragment key={i}>
            <div className="h3eb549cf" onClick={v.go} style={css("padding:4px 12px;border-radius:999px;font-size:10px;font-weight:600;cursor:pointer;background:{{ v.bg }};color:{{ v.fg }};border:1px solid {{ v.bd }}", { v, v })}>{v.label}</div>
          </React.Fragment>))}<div style={css("flex:1", { v })}></div><span style={css("font-size:10px;color:#6b7699", { v })}>{v.rowCount} assets shown</span></div><div style={css("flex:1;margin:0 14px;background:#0a1226;border:1px solid #1c2a4d;border-radius:10px;overflow:auto;min-height:0", { v })}><div style={css("min-width:1500px", { v })}><div style={css("display:grid;grid-template-columns:26px 84px 58px 52px 168px 56px 64px 60px 96px 68px 84px 100px 66px 92px 56px 74px minmax(190px,1fr);gap:0 10px;padding:7px 12px;border-bottom:1px solid #1c2a4d;position:sticky;top:0;background:#0d1730;z-index:2", { v })}>{(v.headers || []).map((h, i) => (<React.Fragment key={i}>
            <div className="h3eb549cf" onClick={h.sort} style={css("font-size:9px;letter-spacing:1px;font-weight:600;cursor:pointer;color:{{ h.fg }};white-space:nowrap", { v, h })}>{h.label}{h.arrow}</div>
          </React.Fragment>))}</div>{(v.rows || []).map((r, i) => (<React.Fragment key={i}>
            <div className="hcf3da810" onClick={r.open} style={css("display:grid;grid-template-columns:26px 84px 58px 52px 168px 56px 64px 60px 96px 68px 84px 100px 66px 92px 56px 74px minmax(190px,1fr);gap:0 10px;align-items:center;padding:6px 12px;border-bottom:1px solid #16223f;cursor:pointer;animation:{{ r.anim }}", { v, r })}><div className="h7a920191" onClick={r.star} style={css("font-size:13px;line-height:1;cursor:pointer;color:{{ r.starColor }}", { v, r })}>{r.starGlyph}</div><div><span style={css("font-size:9px;font-weight:700;letter-spacing:.6px;padding:2.5px 7px;border-radius:10px;background:{{ r.stageBg }};color:{{ r.stageFg }}", { v, r })}>{r.stage}</span></div><div style={css("font-size:15px;font-weight:700;color:{{ r.scoreColor }}", { v, r })}>{r.score}</div><div style={css("color:#8b96b8", { v, r })}>{r.conf}</div><div style={css("min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis", { v, r })}><span style={css("font-weight:700;color:#ffffff", { v, r })}>{r.sym}</span>{r.isBundle && (<>
              <span style={css("font-size:8px;font-weight:800;padding:1.5px 6px;border-radius:999px;background:#45103a;color:#ff4fae;letter-spacing:.4px", { v, r })}>BUNDLE</span>
            </>)}<span style={css("font-size:10px;color:#6b7699", { v, r })}>{r.name}</span></div><div style={css("font-size:10px;font-weight:600;color:{{ r.chainColor }}", { v, r })}>{r.chain}</div><div><span style={css("font-size:9px;padding:2px 5px;border:1px solid {{ r.clsColor }};color:{{ r.clsColor }};border-radius:10px", { v, r })}>{r.cls}</span></div><div style={css("color:#8b96b8", { v, r })}>{r.age}</div><div style={css("color:#dfe6f6", { v, r })}>{r.price}</div><div style={css("font-weight:600;color:{{ r.chgColor }}", { v, r })}>{r.chg}</div><div>{r.liq}</div><div>{r.vol} <span style={css("font-size:9px;color:#6b7699", { v, r })}>{r.volTag}</span></div><div>{r.buyers}</div><div style={css("font-weight:600;color:{{ r.nfColor }}", { v, r })}>{r.netflow}</div><div style={css("font-weight:600;color:{{ r.washColor }}", { v, r })}>{r.wash}</div><div style={css("display:flex;align-items:flex-end;gap:1.5px;height:22px;padding-bottom:2px", { v, r })}>{(r.trend || []).map((tb, i) => (<React.Fragment key={i}>
              <div style={css("width:3.5px;height:{{ tb.h }};background:{{ tb.c }};border-radius:1px", { v, r, tb })}></div>
            </React.Fragment>))}</div><div style={css("font-size:10.5px;color:#a3aed0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis", { v, r })}>{r.reason}</div></div>{r.expanded && (<>
              <div style={css("display:flex;gap:16px;padding:12px 16px;background:#0d1730;border-bottom:1px solid #16223f", { v, r })}><div style={css("width:300px;flex-shrink:0", { v, r })}><div style={css("font-size:9px;letter-spacing:1px;color:#6b7699;font-weight:600;margin-bottom:6px", { v, r })}>PRICE — 1M BARS</div><div style={css("display:flex;align-items:flex-end;gap:2px;height:60px", { v, r })}>{(r.peekSpark || []).map((pb, i) => (<React.Fragment key={i}>
                <div style={css("flex:1;background:{{ pb.c }};height:{{ pb.h }};border-radius:1px 1px 0 0", { v, r, pb })}></div>
              </React.Fragment>))}</div></div><div style={css("flex:1;min-width:0", { v, r })}><div style={css("font-size:9px;letter-spacing:1px;color:#6b7699;font-weight:600;margin-bottom:6px", { v, r })}>TOP TRIGGERS</div>{(r.peekReasons || []).map((pr, i) => (<React.Fragment key={i}>
                <div style={css("display:flex;gap:10px;align-items:baseline;padding:3px 0;font-size:10.5px", { v, r, pr })}><span style={css("width:140px;font-weight:700;color:#e35ff2;flex-shrink:0;font-size:9.5px", { v, r, pr })}>{pr.code}</span><span style={css("flex:1;color:#c6d1ea;white-space:nowrap;overflow:hidden;text-overflow:ellipsis", { v, r, pr })}>{pr.text}</span><span style={css("color:#8b96b8;font-size:10px;flex-shrink:0", { v, r, pr })}>z {pr.z}</span></div>
              </React.Fragment>))}</div><div style={css("width:280px;flex-shrink:0", { v, r })}><div style={css("font-size:9px;letter-spacing:1px;color:#6b7699;font-weight:600;margin-bottom:6px", { v, r })}>RISK</div>{(r.peekFlags || []).map((pf, i) => (<React.Fragment key={i}>
                <div style={css("display:flex;gap:7px;align-items:baseline;padding:3px 0", { v, r, pf })}><span style={css("font-size:8.5px;font-weight:700;padding:2px 8px;border-radius:999px;background:{{ pf.bg }};color:{{ pf.fg }};flex-shrink:0", { v, r, pf })}>{pf.sev}</span><span style={css("font-size:10.5px;color:#c6d1ea", { v, r, pf })}>{pf.text}</span></div>
              </React.Fragment>))}<div onClick={r.goDetail} style={css("margin-top:9px;display:inline-block;padding:5px 16px;border-radius:999px;background:linear-gradient(135deg,#2b6bff,#e35ff2);color:#ffffff;font-size:10px;font-weight:700;cursor:pointer", { v, r })}>OPEN FULL DETAIL →</div></div></div>
            </>)}
          </React.Fragment>))}</div></div><div style={css("display:flex;gap:10px;height:170px;margin:10px 14px 12px;flex-shrink:0", { v })}><div style={css("flex:1;background:#0a1226;border:1px solid #1c2a4d;border-radius:10px;display:flex;flex-direction:column;min-width:0", { v })}><div style={css("padding:6px 12px;border-bottom:1px solid #1c2a4d;font-size:9px;letter-spacing:1.2px;color:#8b96b8;font-weight:600", { v })}>EVENT TAPE — RAW INGESTION (LAYER A)</div><div style={css("flex:1;overflow:hidden;padding:4px 12px", { v })}>{(v.tape || []).map((e, i) => (<React.Fragment key={i}>
            <div style={css("display:flex;gap:12px;padding:2.5px 0;font-size:10.5px;animation:{{ e.anim }}", { v, e })}><span style={css("color:#6b7699", { v, e })}>{e.ts}</span><span style={css("width:74px;font-weight:700;color:{{ e.kindColor }}", { v, e })}>{e.kind}</span><span style={css("width:52px;color:{{ e.chainColor }}", { v, e })}>{e.chain}</span><span style={css("color:#c6d1ea", { v, e })}>{e.text}</span></div>
          </React.Fragment>))}</div></div><div style={css("width:330px;background:#0a1226;border:1px solid #1c2a4d;border-radius:10px;display:flex;flex-shrink:0;overflow:hidden", { v })}><div style={css("flex:1;padding:10px 4px 10px 14px;min-width:0", { v })}><div className="h1813ba3e" onClick={v.openChepePick} style={css("display:flex;align-items:center;gap:5px;margin-bottom:5px;padding:4px 9px;border-radius:999px;background:linear-gradient(135deg,rgba(43,107,255,.25),rgba(227,95,242,.25));border:1px solid #e35ff2;cursor:pointer;white-space:nowrap;overflow:hidden", { v })}><span style={css("font-size:8px;font-weight:800;letter-spacing:.5px;color:#f06ee2;flex-shrink:0", { v })}>DAILY PICK</span><span style={css("font-weight:800;color:#ffffff;font-size:10.5px", { v })}>{v.chepePickSym}</span><span style={css("font-size:9px;color:#8b96b8", { v })}>· {v.chepePickScore}</span></div><div style={css("font-size:8.5px;color:#a3aed0;line-height:1.35;margin-bottom:5px;font-style:italic;overflow:hidden;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical", { v })}>"{v.chepePickQuip}" — not financial advice</div><div style={css("font-size:9px;letter-spacing:1.2px;color:#f06ee2;font-weight:700;margin-bottom:4px", { v })}>CHEPE'S VETO LOG</div>{(v.chepeStats || []).map((cs, i) => (<React.Fragment key={i}>
            <div style={css("display:flex;justify-content:space-between;gap:8px;padding:1.5px 0;font-size:9.5px", { v, cs })}><span style={css("color:#8b96b8;white-space:nowrap;overflow:hidden;text-overflow:ellipsis", { v, cs })}>{cs.k}</span><span style={css("font-weight:700;color:#ffffff;flex-shrink:0", { v, cs })}>{cs.v}</span></div>
          </React.Fragment>))}</div><img src="/assets/chepe.png" alt="Chepe" style={css("width:108px;height:100%;object-fit:cover;object-position:center bottom;flex-shrink:0", { v })} /></div></div></div>
        </>);
}